/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProfileRegistry } from "./ProfileRegistry";
export type { ProfileRegistryV2 } from "./ProfileRegistryV2";
