/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ProfileRegistryV2Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "DECENTRALIZATION_THRESHOLD"
      | "MAX_GUARDIANS"
      | "MIN_GUARDIANS"
      | "MIN_TIME_LOCK_HOURS"
      | "UPGRADE_INTERFACE_VERSION"
      | "cancelRecovery"
      | "completeRecovery"
      | "configureRecovery"
      | "getGuardians"
      | "getPendingRecovery"
      | "getProfile"
      | "getRecoveryConfig"
      | "guardians"
      | "initialize"
      | "initiateRecovery"
      | "isDecentralized"
      | "isGuardian"
      | "lastUpdated"
      | "multisig"
      | "multisigRequired"
      | "owner"
      | "pause"
      | "paused"
      | "profiles"
      | "proxiableUUID"
      | "recoveryConfigs"
      | "renounceOwnership"
      | "setMultisig"
      | "totalUsers"
      | "transferOwnership"
      | "unpause"
      | "updateProfile"
      | "upgradeToAndCall"
      | "usersUntilDecentralization"
      | "version"
      | "voteForRecovery"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GuardianAdded"
      | "GuardianRemoved"
      | "Initialized"
      | "MultisigActivated"
      | "MultisigUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "ProfileUpdated"
      | "RecoveryCancelled"
      | "RecoveryCompleted"
      | "RecoveryConfigured"
      | "RecoveryInitiated"
      | "RecoveryVoteSubmitted"
      | "Unpaused"
      | "Upgraded"
      | "UserRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DECENTRALIZATION_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_GUARDIANS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_GUARDIANS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_TIME_LOCK_HOURS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRecovery",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "completeRecovery",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "configureRecovery",
    values: [AddressLike[], BigNumberish, BigNumberish, string[], BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardians",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRecovery",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecoveryConfig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "guardians",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateRecovery",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDecentralized",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isGuardian",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastUpdated",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "multisig", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "multisigRequired",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "profiles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoveryConfigs",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMultisig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalUsers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateProfile",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "usersUntilDecentralization",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voteForRecovery",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DECENTRALIZATION_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_GUARDIANS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_GUARDIANS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_TIME_LOCK_HOURS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardians",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecoveryConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "guardians", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateRecovery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDecentralized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isGuardian", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastUpdated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multisig", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multisigRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "profiles", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoveryConfigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "usersUntilDecentralization",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteForRecovery",
    data: BytesLike
  ): Result;
}

export namespace GuardianAddedEvent {
  export type InputTuple = [user: AddressLike, guardian: AddressLike];
  export type OutputTuple = [user: string, guardian: string];
  export interface OutputObject {
    user: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianRemovedEvent {
  export type InputTuple = [user: AddressLike, guardian: AddressLike];
  export type OutputTuple = [user: string, guardian: string];
  export interface OutputObject {
    user: string;
    guardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigActivatedEvent {
  export type InputTuple = [userCount: BigNumberish];
  export type OutputTuple = [userCount: bigint];
  export interface OutputObject {
    userCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultisigUpdatedEvent {
  export type InputTuple = [oldMultisig: AddressLike, newMultisig: AddressLike];
  export type OutputTuple = [oldMultisig: string, newMultisig: string];
  export interface OutputObject {
    oldMultisig: string;
    newMultisig: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [
    user: AddressLike,
    cid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, cid: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    cid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryCancelledEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryCompletedEvent {
  export type InputTuple = [user: AddressLike, newCid: string];
  export type OutputTuple = [user: string, newCid: string];
  export interface OutputObject {
    user: string;
    newCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryConfiguredEvent {
  export type InputTuple = [
    user: AddressLike,
    guardianCount: BigNumberish,
    threshold: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    guardianCount: bigint,
    threshold: bigint
  ];
  export interface OutputObject {
    user: string;
    guardianCount: bigint;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryInitiatedEvent {
  export type InputTuple = [
    user: AddressLike,
    initiator: AddressLike,
    completesAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    initiator: string,
    completesAt: bigint
  ];
  export interface OutputObject {
    user: string;
    initiator: string;
    completesAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryVoteSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    guardian: AddressLike,
    totalVotes: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    guardian: string,
    totalVotes: bigint
  ];
  export interface OutputObject {
    user: string;
    guardian: string;
    totalVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserRegisteredEvent {
  export type InputTuple = [user: AddressLike, totalUsers: BigNumberish];
  export type OutputTuple = [user: string, totalUsers: bigint];
  export interface OutputObject {
    user: string;
    totalUsers: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProfileRegistryV2 extends BaseContract {
  connect(runner?: ContractRunner | null): ProfileRegistryV2;
  waitForDeployment(): Promise<this>;

  interface: ProfileRegistryV2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DECENTRALIZATION_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_GUARDIANS: TypedContractMethod<[], [bigint], "view">;

  MIN_GUARDIANS: TypedContractMethod<[], [bigint], "view">;

  MIN_TIME_LOCK_HOURS: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  cancelRecovery: TypedContractMethod<[], [void], "nonpayable">;

  completeRecovery: TypedContractMethod<
    [user: AddressLike, newCid: string],
    [void],
    "nonpayable"
  >;

  configureRecovery: TypedContractMethod<
    [
      _guardians: AddressLike[],
      _threshold: BigNumberish,
      _timeLockHours: BigNumberish,
      _shareCids: string[],
      _verificationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getGuardians: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  getPendingRecovery: TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean, bigint] & {
        initiator: string;
        initiatedAt: bigint;
        votesReceived: bigint;
        cancelled: boolean;
        completed: boolean;
        timeLockEnd: bigint;
      }
    ],
    "view"
  >;

  getProfile: TypedContractMethod<[user: AddressLike], [string], "view">;

  getRecoveryConfig: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, string[], string, boolean] & {
        timeLockHours: bigint;
        threshold: bigint;
        shareCids: string[];
        verificationHash: string;
        configured: boolean;
      }
    ],
    "view"
  >;

  guardians: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  initialize: TypedContractMethod<
    [_multisig: AddressLike],
    [void],
    "nonpayable"
  >;

  initiateRecovery: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  isDecentralized: TypedContractMethod<[], [boolean], "view">;

  isGuardian: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  lastUpdated: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  multisig: TypedContractMethod<[], [string], "view">;

  multisigRequired: TypedContractMethod<[], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  profiles: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  recoveryConfigs: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, string, boolean] & {
        timeLockHours: bigint;
        threshold: bigint;
        verificationHash: string;
        configured: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMultisig: TypedContractMethod<
    [_newMultisig: AddressLike],
    [void],
    "nonpayable"
  >;

  totalUsers: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateProfile: TypedContractMethod<[cid: string], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  usersUntilDecentralization: TypedContractMethod<[], [bigint], "view">;

  version: TypedContractMethod<[], [string], "view">;

  voteForRecovery: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DECENTRALIZATION_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_GUARDIANS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_GUARDIANS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_TIME_LOCK_HOURS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelRecovery"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeRecovery"
  ): TypedContractMethod<
    [user: AddressLike, newCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureRecovery"
  ): TypedContractMethod<
    [
      _guardians: AddressLike[],
      _threshold: BigNumberish,
      _timeLockHours: BigNumberish,
      _shareCids: string[],
      _verificationHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getGuardians"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPendingRecovery"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [string, bigint, bigint, boolean, boolean, bigint] & {
        initiator: string;
        initiatedAt: bigint;
        votesReceived: bigint;
        cancelled: boolean;
        completed: boolean;
        timeLockEnd: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRecoveryConfig"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, string[], string, boolean] & {
        timeLockHours: bigint;
        threshold: bigint;
        shareCids: string[];
        verificationHash: string;
        configured: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "guardians"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[_multisig: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "initiateRecovery"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isDecentralized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isGuardian"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lastUpdated"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "multisig"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "multisigRequired"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "profiles"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recoveryConfigs"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, string, boolean] & {
        timeLockHours: bigint;
        threshold: bigint;
        verificationHash: string;
        configured: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMultisig"
  ): TypedContractMethod<[_newMultisig: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalUsers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateProfile"
  ): TypedContractMethod<[cid: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "usersUntilDecentralization"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "voteForRecovery"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "GuardianAdded"
  ): TypedContractEvent<
    GuardianAddedEvent.InputTuple,
    GuardianAddedEvent.OutputTuple,
    GuardianAddedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianRemoved"
  ): TypedContractEvent<
    GuardianRemovedEvent.InputTuple,
    GuardianRemovedEvent.OutputTuple,
    GuardianRemovedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MultisigActivated"
  ): TypedContractEvent<
    MultisigActivatedEvent.InputTuple,
    MultisigActivatedEvent.OutputTuple,
    MultisigActivatedEvent.OutputObject
  >;
  getEvent(
    key: "MultisigUpdated"
  ): TypedContractEvent<
    MultisigUpdatedEvent.InputTuple,
    MultisigUpdatedEvent.OutputTuple,
    MultisigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryCancelled"
  ): TypedContractEvent<
    RecoveryCancelledEvent.InputTuple,
    RecoveryCancelledEvent.OutputTuple,
    RecoveryCancelledEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryCompleted"
  ): TypedContractEvent<
    RecoveryCompletedEvent.InputTuple,
    RecoveryCompletedEvent.OutputTuple,
    RecoveryCompletedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryConfigured"
  ): TypedContractEvent<
    RecoveryConfiguredEvent.InputTuple,
    RecoveryConfiguredEvent.OutputTuple,
    RecoveryConfiguredEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryInitiated"
  ): TypedContractEvent<
    RecoveryInitiatedEvent.InputTuple,
    RecoveryInitiatedEvent.OutputTuple,
    RecoveryInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryVoteSubmitted"
  ): TypedContractEvent<
    RecoveryVoteSubmittedEvent.InputTuple,
    RecoveryVoteSubmittedEvent.OutputTuple,
    RecoveryVoteSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "UserRegistered"
  ): TypedContractEvent<
    UserRegisteredEvent.InputTuple,
    UserRegisteredEvent.OutputTuple,
    UserRegisteredEvent.OutputObject
  >;

  filters: {
    "GuardianAdded(address,address)": TypedContractEvent<
      GuardianAddedEvent.InputTuple,
      GuardianAddedEvent.OutputTuple,
      GuardianAddedEvent.OutputObject
    >;
    GuardianAdded: TypedContractEvent<
      GuardianAddedEvent.InputTuple,
      GuardianAddedEvent.OutputTuple,
      GuardianAddedEvent.OutputObject
    >;

    "GuardianRemoved(address,address)": TypedContractEvent<
      GuardianRemovedEvent.InputTuple,
      GuardianRemovedEvent.OutputTuple,
      GuardianRemovedEvent.OutputObject
    >;
    GuardianRemoved: TypedContractEvent<
      GuardianRemovedEvent.InputTuple,
      GuardianRemovedEvent.OutputTuple,
      GuardianRemovedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MultisigActivated(uint256)": TypedContractEvent<
      MultisigActivatedEvent.InputTuple,
      MultisigActivatedEvent.OutputTuple,
      MultisigActivatedEvent.OutputObject
    >;
    MultisigActivated: TypedContractEvent<
      MultisigActivatedEvent.InputTuple,
      MultisigActivatedEvent.OutputTuple,
      MultisigActivatedEvent.OutputObject
    >;

    "MultisigUpdated(address,address)": TypedContractEvent<
      MultisigUpdatedEvent.InputTuple,
      MultisigUpdatedEvent.OutputTuple,
      MultisigUpdatedEvent.OutputObject
    >;
    MultisigUpdated: TypedContractEvent<
      MultisigUpdatedEvent.InputTuple,
      MultisigUpdatedEvent.OutputTuple,
      MultisigUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "ProfileUpdated(address,string,uint256)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;

    "RecoveryCancelled(address)": TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;
    RecoveryCancelled: TypedContractEvent<
      RecoveryCancelledEvent.InputTuple,
      RecoveryCancelledEvent.OutputTuple,
      RecoveryCancelledEvent.OutputObject
    >;

    "RecoveryCompleted(address,string)": TypedContractEvent<
      RecoveryCompletedEvent.InputTuple,
      RecoveryCompletedEvent.OutputTuple,
      RecoveryCompletedEvent.OutputObject
    >;
    RecoveryCompleted: TypedContractEvent<
      RecoveryCompletedEvent.InputTuple,
      RecoveryCompletedEvent.OutputTuple,
      RecoveryCompletedEvent.OutputObject
    >;

    "RecoveryConfigured(address,uint256,uint256)": TypedContractEvent<
      RecoveryConfiguredEvent.InputTuple,
      RecoveryConfiguredEvent.OutputTuple,
      RecoveryConfiguredEvent.OutputObject
    >;
    RecoveryConfigured: TypedContractEvent<
      RecoveryConfiguredEvent.InputTuple,
      RecoveryConfiguredEvent.OutputTuple,
      RecoveryConfiguredEvent.OutputObject
    >;

    "RecoveryInitiated(address,address,uint256)": TypedContractEvent<
      RecoveryInitiatedEvent.InputTuple,
      RecoveryInitiatedEvent.OutputTuple,
      RecoveryInitiatedEvent.OutputObject
    >;
    RecoveryInitiated: TypedContractEvent<
      RecoveryInitiatedEvent.InputTuple,
      RecoveryInitiatedEvent.OutputTuple,
      RecoveryInitiatedEvent.OutputObject
    >;

    "RecoveryVoteSubmitted(address,address,uint256)": TypedContractEvent<
      RecoveryVoteSubmittedEvent.InputTuple,
      RecoveryVoteSubmittedEvent.OutputTuple,
      RecoveryVoteSubmittedEvent.OutputObject
    >;
    RecoveryVoteSubmitted: TypedContractEvent<
      RecoveryVoteSubmittedEvent.InputTuple,
      RecoveryVoteSubmittedEvent.OutputTuple,
      RecoveryVoteSubmittedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "UserRegistered(address,uint256)": TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
    UserRegistered: TypedContractEvent<
      UserRegisteredEvent.InputTuple,
      UserRegisteredEvent.OutputTuple,
      UserRegisteredEvent.OutputObject
    >;
  };
}
