/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ProfileRegistry__factory } from "./ProfileRegistry__factory";
export { ProfileRegistryV2__factory } from "./ProfileRegistryV2__factory";
